name: 'Create a binary artifact for Node on Alpine Linux'
description: 'Create a binary artifact for Node on Alpine Linux using musl'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '12'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.node-version}}
